# DigitalOcean App Platform Configuration
name: card-collector-web
services:
- name: web
  source_dir: /
  github:
    repo: your-username/card-collector
    branch: main
  run_command: python -m uvicorn web.app:app --host 0.0.0.0 --port 8080
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /api/health
  envs:
  - key: DISCORD_BOT_TOKEN
    scope: RUN_TIME
    type: SECRET
  - key: JWT_SECRET_KEY
    scope: RUN_TIME  
    type: SECRET
  - key: DATABASE_URL
    value: sqlite+aiosqlite:///./card_collector.db
    scope: RUN_TIME
  - key: WEB_HOST
    value: 0.0.0.0
    scope: RUN_TIME
  - key: WEB_PORT
    value: "8080"
    scope: RUN_TIME
  - key: DEBUG
    value: "false"
    scope: RUN_TIME
  - key: LOG_LEVEL
    value: INFO
    scope: RUN_TIME